repository: azure/azure-sdk


tipue_search:
  include:
    pages: true
    posts: true

# feed.xml
title: Azure SDKs
description: "The design guidelines and policies under which the Azure SDKs are designed and built."
topnav_title: Azure SDKs
site_title: Azure SDKs
company_name: Microsoft Azure

# github_editme_path: azure/azure-sdk/blob/gh-pages/
# disqus_shortname: azure-sdk
google_analytics: UA-62780441-46
app_insights: 5e03f19a-f5b4-4620-97d5-35707cec7fcb

# The preview server settings
host: 127.0.0.1
port: 4000
baseurl: /azure-sdk
destination: ./_site/azure-sdk
output: web

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

# Files and directories that Jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - eng
  - vendor
  - docs/policies/README*

feedback_subject_line: Azure SDK Design Guidelines Feedback
feedback_email: adparch@microsoft.com
feedback_disable: true

# Social Profiles
twitter:
  username: azuresdk
  card: summary

social:
  name: Azure SDKs
  links:
    - https://twitter.com/AzureSDK
    - https://github.com/azure/azure-sdk

blog_url: https://devblogs.microsoft.com/azure-sdk/

# Various plugin settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

timezone: "US/Pacific"

relative_links:
  enabled: true
  collections: true
  
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: general_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post_redirect"
      comments: false
      search: true
      sidebar: general_sidebar
      topnav: topnav
      permalink: /posts/:year-:month-:day/:title:output_ext

sidebars:
  - general_sidebar

github: [metadata]
