repository: azure/azure-sdk

# feed.xml
title: Azure SDKs
description: "The design guidelines and policies under which the Azure SDKs are designed and built."
topnav_title: Azure SDKs
site_title: Azure SDKs
company_name: Microsoft Azure

# github_editme_path: azure/azure-sdk/blob/gh-pages/
# disqus_shortname: azure-sdk
google_analytics: UA-151056387-1

# The preview server settings
host: 127.0.0.1
port: 4000
output: web

plugins_dir:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

# Files and directories that Jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - eng
  - vendor

feedback_subject_line: Azure SDK Design Guidelines Feedback
feedback_email: adparch@microsoft.com
feedback_disable: true

# Social Profiles
twitter:
  username: azuresdk
  card: summary

social:
  name: Azure SDKs
  links:
    - https://twitter.com/AzureSDK
    - https://github.com/azure/azure-sdk

# Various plugin settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

paginate: 10
paginate_path: /page:num/
timezone: "US/Pacific"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav
      permalink: /posts/:year-:month-:day/:title:output_ext

sidebars:
  - home_sidebar

github: [metadata]
